version: "3.7"
services:
  roubar:
    build: ./
    expose:
      - "3024"
    command: >
      bash -c "mix phx.server"
    volumes:
      - ./roubar:/app
    ports:
      - "3024:3024"
    env_file:
      - ".env"
    tty: true
    stdin_open: true